# تكوين روبوت Stale لإدارة المشكلات وطلبات السحب غير النشطة

# عدد الأيام قبل وضع علامة على المشكلة أو طلب السحب كغير نشط
daysUntilStale: 60

# عدد الأيام قبل إغلاق المشكلة أو طلب السحب غير النشط
daysUntilClose: 7

# المشكلات ذات هذه التسميات لن تتم إدارتها بواسطة روبوت Stale
exemptLabels:
  - pinned
  - security
  - bug
  - enhancement
  - documentation
  - good first issue
  - help wanted

# تسمية لاستخدامها عند وضع علامة على المشكلة كغير نشطة
staleLabel: wontfix

# تعليق لنشره عند وضع علامة على المشكلة كغير نشطة
markComment: >
  تم وضع علامة على هذه المشكلة تلقائيًا كغير نشطة بسبب عدم وجود نشاط حديث.
  سيتم إغلاقها إذا لم يكن هناك نشاط إضافي. شكرًا لمساهمتك في JawaL!
  إذا كنت تعتقد أن هذه المشكلة لا تزال ذات صلة، يرجى الرد على هذا التعليق.

# تعليق لنشره عند إغلاق المشكلة
closeComment: >
  تم إغلاق هذه المشكلة تلقائيًا بسبب عدم وجود نشاط إضافي.
  يرجى إعادة فتح مشكلة جديدة إذا كنت لا تزال تواجه المشكلة.

# محتوى البحث عن المشكلات وطلبات السحب
only: issues